image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - npm install && npm test
        - step:
            name: Build
            script:
              - npm install && npm run build
            artifacts:
              - build/**
        - step:
            name: Deploy to Firbase
            deployment: production
            script:
              - ls -R
              - echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > firebase-key.json
              - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-key.json
              - npm install -g firebase-tools
              - firebase deploy --project $FIREBASE_TOKEN
